#

name: build-form-app,
on:
    push:
      branches:
        - '**'
      tags:
        - '**'
jobs:
    build-test-lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: '18.x'
                cache: 'npm'
            - run: make install
            # - run: make test // will be added after
            - run: make lint
            - run: make exec
            - uses: hexlet-components/hello-from-hexlet-action@release



